## Session name :- Operators ||  Date :- 27/07/2026

There are 7 types of operator. 
1) Arthmetic (+,-,*,/,%,//)
2) Comparision/Relational (>,<,>=,<=)
3) Logical (or,and,not)
4) Assingment Operator (=,+=,-=,*=,/=)
5) Membership (in,not in)
6) Identity (is,is not)
7) Bitwise (|,&,^,>>,<<)

### 1) Arthmetic operator

In [16]:
a=20
b=7

print("Addition",a+b)
print("Substraction",a-b)
print("Multiplication",a*b)
print("Division",a/b) # quotient with point
print("Modulo",a%b) #reminder
print("Floor Division",a//b) #quotient with whole number
print("Power",a**2)

Addition 27
Substraction 13
Multiplication 140
Division 2.857142857142857
Modulo 6
Floor Division 2
Power 400


### 2) Comparision / Relational Operator

In [2]:
a=30
b=9

print("double equal to",a==b)
print("greater than", a>b)
print("less than",a<b)
print("grater than or equal to",a>=b)
print("less than or equal to", a<=b)
print("not equal to", a!=b)


double equal to False
greater than True
less than False
grater than or equal to True
less than or equal to False
not equal to True


### 3) Logical Operator

1) or
2) and
3) not
   

In [3]:
a = True
b = False

In [4]:
print(a or b)
print(a and b)
print(not a)

True
False
False


### 4) Assingment Operator

In [5]:
a = 20
b = 7 #equal to 

In [6]:
a+=b
print("add and equal to", a)

a-=b
print("sub and equal to", a)

a*=b
print("Multi and equal to", a)

a/=b
print("Div and equal to", a)

a%=b
print("modulo and equal to", a)

a//=b
print("FLoor DIv and equal to", a)

add and equal to 27
sub and equal to 20
Multi and equal to 140
Div and equal to 20.0
modulo and equal to 6.0
FLoor DIv and equal to 0.0


### 5) Membership
1) in
2) not in

In [7]:
l1=[41,54,68,79,54,65]

if 41 in l1:
    print("It is inside the list")
else:
    print("It is not inside the list")

It is inside the list


### 6) Identity 
1) is
2) is not

In [8]:
a=30
b=29

a is b 

False

In [9]:
a is not b

True

### 7) Bitwise

1) OR (|)
2) AND (&)
3) XOR (^)
4) Right SHift (>>)
5) Left Shift (<<)

In [11]:
7 | 2 # oR


7

In [12]:
7 & 2  #AND


2

In [13]:
7 ^ 2 #XOR

5

In [14]:
7 >> 2 #right shift

1

In [15]:
7<<2 #left shift

28

## Session Name :- Conditional Statement || Date :- 28/07/2026 

- There are 3 types of Coditional Statement
 1) if
 2) if-else
 3) if-elif-else

### Conditional  

- Conditional statements allow a program to make dicisions based on coditions. They execute different blocks of code depending on whether a codition True or False

#### 1) If-statement

- Executes a block only if codintion is True

In [10]:
""" syntax 
if codition:
     code """

' syntax \nif codition:\n     code '

In [11]:
age = int(input("Enter Your Age"))

if age > 18:
    print("You are Eligible for voting")
    

Enter Your Age 22


You are Eligible for voting


#### 2) if-else Statement

- Execute one block if the condition is True; otherwise executes another block.

In [14]:
n1 = int(input("Enter the first number"))
n2 = int(input("Enter the second number"))

if n1 > n2 :
    print(f"{n1} is greater than {n2} ")
else :
    print(f"{n2} is greater than {n1} ")

Enter the first number 34
Enter the second number 23


34 is greater than 23 


#### 3) if-elif-else statement

- Used to check multiple conditions

In [20]:
age = int(input("Enter Your Age"))

if age >= 18 :
    print("You are Eligible for Vote")
elif age <= 0 :
    print("Invalid Input")
else:
    print("You are not eligible for the vote")

Enter Your Age 18


You are Eligible for Vote


In [25]:
marks = int(input("Enter Your Marks"))

if marks >= 75 :
    print("Distinction")
elif 60 <= marks < 75:
    print("first class with distction")
elif 40 <= marks <60 :
    print("second class with distiction")
elif marks < 35:
    print("Fail")

Enter Your Marks 22


Fail


In [34]:
n1 = int(input("Enter your 1st no."))
n2 = int(input("Enter your 2nd no."))
n3 = int(input("Enter your 3rd no."))

if (n1 > n2) and (n1 > n3):
    print(f"The {n1} is greater than {n2} and {n3}")
    
elif (n2 > n1) and (n2 > n3):
    print(f"The {n2} is greater than {n1} and {n3}")
    
else:
    print(f"The {n3} is greater than {n1} and {n2}")
    

Enter your 1st no. 5
Enter your 2nd no. 89
Enter your 3rd no. 23


The 89 is greater than 5 and 23


In [38]:
n = int(input("Enter Your Number to check odd and even"))

if n%2 == 0:
    print(f"The {n} is even number")
else:
    print(f"The {n} is Odd number")

Enter Your Number to check odd and even 5


The 5 is Odd number


## Session Name :- Loops & Control Statement || Date :- 29/07/2026

- Loops
1) for
2) while

- Control Statement
1) break
2) continue
3) pass

### Loops Statements

- Iterates over a sequence
- We can use for list , string, tuple or with range functions

#### For Loop

In [3]:
for i in range(1,11):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 

In [4]:
list(range(0,10,3))

[0, 3, 6, 9]

In [6]:
list(range(-10,-100,-30))

[-10, -40, -70]

In [16]:
for i in range(50,0,-1):
    print(i,end=" ")


50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 

In [18]:
for i in range(1,11):
    print(f"{21} * {i} = {21*i}")

21 * 1 = 21
21 * 2 = 42
21 * 3 = 63
21 * 4 = 84
21 * 5 = 105
21 * 6 = 126
21 * 7 = 147
21 * 8 = 168
21 * 9 = 189
21 * 10 = 210


In [21]:
n = int(input("Enter Number"))
for i in range(1,11):
    print(f"{n} * {i} = {n*i}")

Enter Number 23


23 * 1 = 23
23 * 2 = 46
23 * 3 = 69
23 * 4 = 92
23 * 5 = 115
23 * 6 = 138
23 * 7 = 161
23 * 8 = 184
23 * 9 = 207
23 * 10 = 230


In [23]:
#Iterate through String
name = "Python"

for ch in name:
    print(ch,end="     ")

P     y     t     h     o     n     

In [25]:
#Iterate through 
Fruits = ["Apple", "Mango","Banana" ]
for fruit in Fruits:
    print(fruit, end="        ")

Apple        Mango        Banana        

#### Nested Loop

- Nested loop inside a loop
- The "inner loop" will be executed for each iteration of outer loop

In [29]:
for i in range(3):
    for j in range(4):
        print(i,j)

0 0
0 1
0 2
0 3
1 0
1 1
1 2
1 3
2 0
2 1
2 2
2 3


In [30]:
for i in range(5):
    for j in range(5):
        print("*", end = " ")
    print()

* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


#### While Loop

- Repeats a block as long as its codition stays True. Best when you don't know how many times you will need to loop

In [47]:
i = 1

while (i < 51):
    print(i,end =" ")
    i = i+1

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 

In [3]:
n = 21
i=1
while i < 11:
    print(f"{n} * {i} = {n*i}")
    i = i+1

21 * 1 = 21
21 * 2 = 42
21 * 3 = 63
21 * 4 = 84
21 * 5 = 105
21 * 6 = 126
21 * 7 = 147
21 * 8 = 168
21 * 9 = 189
21 * 10 = 210


In [4]:
n = int(input("Enter the Number"))
i=1
while i < 11:
    print(f"{n} * {i} = {n*i}")
    i = i+1

Enter the Number 54


54 * 1 = 54
54 * 2 = 108
54 * 3 = 162
54 * 4 = 216
54 * 5 = 270
54 * 6 = 324
54 * 7 = 378
54 * 8 = 432
54 * 9 = 486
54 * 10 = 540


### Control Statements

#### break

- It will stop exectution when condition is true

In [7]:
i=1
while(i<=50):
    print(i,end=" ")
    i = i+1
    if i == 25:
        break

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 

#### Continue

In [18]:
i=0
while(i<=50):
    i = i+1
    if i == 25:
        continue
    print(i,end=" ")
    

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 

#### Pass

In [19]:
i=0
while(i<=50):
    i = i+1
    if i == 25:
        pass
    print(i,end=" ")
    

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 

#### Scenario based Question

In [2]:
patient_list = []
count = 0
while True:
    patient_name = input("Enter Your Name")
    print()
    print(f"Welcome to Sanjivani Hostpital {patient_name}!...please wait until your turn")
    count+=1
    patient_list.append(patient_name)
    
    doctor= input("Would You like Send new Patient (yes/no)")
    print()
    if doctor.lower() == 'no' or doctor.lower() == 'n':
        print(f"The hospital is closed please come back tommorow")
        print()
        print(f"Todays Patient List {patient_list}")
        break
    elif doctor.lower() == 'yes' or doctor.lower() == 'y':
        print(f"Patient Number {count} please come")
        print()

Enter Your Name yash



Welcome to Sanjivani Hostpital yash!...please wait until your turn


Would You like Send new Patient (yes/no) y



Patient Number 1 please come



Enter Your Name n



Welcome to Sanjivani Hostpital n!...please wait until your turn


Would You like Send new Patient (yes/no) n



The hospital is closed please come back tommorow

Todays Patient List ['yash', 'n']


## Session Name :- Program || Date :- 30/07/2026

In [5]:
l1 = [20,54,87,95,45,64]
count=0
for i in l1:
    count += i
print(count)


365


In [7]:
user = input("enter your string")
count = 0
for ch in user:
    count += 1
print(count)

enter your string hello


5


In [8]:
numbers = [10,45,-20,54,-90,-38]
count = 0

for i in numbers:
    if i > 0 :
        count += 1

print(count)

3


In [10]:
l2 = [11,45,65,20,99,-999]
max1=0
for i in l2 :
    if max1 < i:
        max1=i
print(max1)

99


In [11]:
l1 =[45,87,65,89,45,22,78,98,20,16]
l2=[]
for i in l1:
    if i%2==0:
        l2.append(i)
print(f"The Even Numebers :- {l2}")

The Even Numebers :- [22, 78, 98, 20, 16]


In [23]:
# write a python program to check wheather a string is palindrome
string= input("Enter the string to check wheather it palindrome or not")
reverse=""
for i in range(len(string)-1,-1,-1):
    reverse = reverse + string[i]
    
if reverse == string:
    print("string is palindrome")
else:
    print("string is not palindrome")

Enter the string to check wheather it palindrome or not Nitin


string is not palindrome


In [6]:
# write a python program to remove duplicate characters 
string = input("Enter the string")
after_dupli=""

for i in string:
    if i not in after_dupli:
        after_dupli += i

print(after_dupli)

Enter the string google


gole


In [1]:
# take a list add some string values and find out largest string from it
Fruits = ["Apple","Pinapple","banana","Mango","Cherry","Grapes"]
max1 = 0
for fruit in Fruits:
    if max1< len(fruit):
        max1 = len(fruit)
for fruit in Fruits:
    if len(fruit) == max1:
        print(f"largest String From List {fruit}")

largest String From List Pinapple


In [3]:
Fruits = ["Apple","Pinapple","banana","Mango","Cherry","Grapes"]
longest=Fruits[0]
for i in Fruits:
    if len(i) > len(longest):
        longest = i
print(f"{longest}")

Pinapple


## Session Name :-  || Date :- 31/07/2026

In [15]:
 print(type('1.2'))

<class 'str'>


In [16]:
 type(1.2)

float

In [1]:
 print(1.0 - 2.0j.real)

1.0


## Session Name :- Python Revision  || Date :- 04/08/2026

### Python for Data Science

- Python is a high-level, interpreted, object-oriented, and general-purpose programming language.

- Python is one of the most popular programming languages because it is: - Easy to learn - Easy to read - Powerful and versatile

- Widely used in Data Science, AI, Machine Learning, Web Development, Automation, and Cloud Computing.

### History of Python
- **📅 Origin (1989–1991)**  
  Python was created by **Guido van Rossum** at the **Centrum Wiskunde & Informatica (CWI)** in the Netherlands. Development started in **December 1989** as a holiday project, and the first official version of Python was released in **1991**.

- **💡 Inspiration & Development**  
  Python was inspired by the **ABC Programming Language**.

- **🎭 Why the Name "Python"?**  
  The name **Python** was inspired by the BBC comedy show **_Monty Python's Flying Circus_**. Guido chose the name because it was **short, unique, and memorable**, rather than being related to the snake.

### Features of Python

Python is a **high-level, interpreted, open-source, and dynamically typed** programming language. It is widely used because of its simplicity, flexibility, and powerful features.

#### ✨ Key Features

- **📝 Easy to Learn & Code**
- **🆓 Free & Open Source**
- **🏗️ Object-Oriented Programming (OOP)**
- **⚡ Interpreted Language**
- **🔄 Dynamically Typed**
  - No need to declare variable data types.
  - Variable types are determined automatically at runtime.

- **🌐 Platform Independent**
- **📚 Large Standard Library**
- **🖥️ GUI Support**
  - Can build desktop applications using libraries like **Tkinter**, **PyQt**, and **wxPython**.

- **🔗 Extensible & Integrable**
  - Can be integrated with languages like **C**, **C++**, and **Java**.

- **🚀 High-Level Language**
  - Simplifies programming by handling memory management automatically.

### Anaconda Python Distribution

**Anaconda** is a free, open-source distribution of **Python** and **R** designed for **Data Science, Machine Learning, Artificial Intelligence, and Scientific Computing**.

#### ✨ Key Features

- **Package Management**
  - Comes with **Conda**, a powerful package manager to install and update libraries easily.

- **Environment Management**
  - Create and manage separate Python environments for different projects.

- **Pre-installed Libraries**
  - Includes popular libraries like **NumPy**, **Pandas**, **Matplotlib**, **Scikit-learn**, **SciPy**, and **Jupyter Notebook**.

- **Easy Installation**
  - Installs Python and essential data science tools in a single setup.

- **Cross-Platform**
  - Available for **Windows**, **Linux**, and **macOS**.

- **Ideal for Data Science**
  - Widely used by **Data Scientists**, **Machine Learning Engineers**, **Researchers**, and **Developers**.

####  Real-World Use Cases of Python

| Company | Real-World Use Case |
|----------|---------------------|
| **YouTube** | World's largest video-sharing platform uses Python for video streaming, backend services, and system management. |
| **Instagram** | Relies on Python (Django) to scale its platform and efficiently handle millions of users and requests every day. |
| **Spotify** | Uses Python for backend development, data analysis, and machine learning to provide personalized music recommendations. |
| **Dropbox** | Built much of its desktop client and server-side infrastructure using Python for file synchronization and cloud storage. |
| **Netflix** | Uses Python for recommendation systems, automation, data analysis, and content delivery optimization (CDN). |
| **Google** | Python is one of Google's primary programming languages for web crawling, testing, automation, and data analysis. |
| **Uber** | Uses Python for backend services, dynamic pricing (surge pricing), route optimization, and machine learning models. |
| **Pinterest** | Uses Python to process, analyze, and store massive volumes of image data while supporting millions of users. |

                         

### Applications of Python

| Domain | Popular Tools / Libraries | Description |
|--------|----------------------------|-------------|
| 🌐 **Web Development** | Django, Flask, FastAPI | Build dynamic, secure, and scalable web applications and REST APIs. |
| 📊 **Data Science & Analysis** | Pandas, NumPy, Matplotlib, Seaborn | Clean, analyze, visualize, and manipulate large datasets. |
| 🤖 **Machine Learning & AI** | Scikit-learn, TensorFlow, PyTorch, Keras | Build predictive models, recommendation systems, and AI applications. |
| ⚙️ **Automation & Scripting** | Built-in Python Libraries | Automate repetitive tasks like file handling, email sending, report generation, and system administration. |
| 🎮 **Game Development** | Pygame | Develop 2D games, educational games, and game prototypes. |
| 🕸️ **Web Scraping** | BeautifulSoup, Scrapy, Selenium | Extract data from websites for research, analytics, and automation. |
| 🖥️ **Desktop Application Development** | Tkinter, PyQt, Kivy | Create cross-platform desktop applications with graphical user interfaces (GUI). |
| 🔬 **Scientific Computing** | SciPy, SymPy | Perform mathematical computations, simulations, optimization, and symbolic mathematics. |
| 🌐 **Internet of Things (IoT)** | MicroPython, Raspberry Pi | Develop embedded systems, smart devices, robotics, and IoT applications. |
| ☁️ **DevOps & Cloud Automation** | Boto3, Ansible, Docker SDK | Automate cloud infrastructure, deployments, CI/CD pipelines, and server management. |
| 🔒 **Cybersecurity** | Scapy, Paramiko, Nmap, Pwntools | Perform penetration testing, network analysis, ethical hacking, and security automation. |


###  Variables in Python

A **variable** is a named memory location used to store data. It acts as a container that holds values, which can be changed during program execution.

#### Syntax

```python
variable_name = value
```

#### Example

```python
name = "Mayur"
age = 25
salary = 50000
is_student = False

print(name)
print(age)
print(salary)
print(is_student)
```

### Rules for Naming Variables

#### Valid Rules

- Variable names can contain **letters (A-Z, a-z), digits (0-9), and underscores (_)**.
- A variable name **must start with a letter or an underscore (_)**.
- Variable names are **case-sensitive** (`age`, `Age`, and `AGE` are different variables).
- Use **meaningful names** for better readability.

##### Valid Examples

```python
name = "John"
_age = 25
student1 = "Rahul"
total_marks = 450
price2025 = 199.99
```

##### Invalid Variable Names

- Cannot start with a number.
- Cannot contain spaces.
- Cannot use special characters like `@`, `#`, `$`, `%`, `&`.
- Cannot use Python keywords (`if`, `for`, `while`, `class`, etc.).


In [3]:
x = 7
y = 3.14
z = "Hi"

In [4]:
# Dynamic Typing: Python is dynamically typed, so the same variable can store different data types during execution.
x = 10
x = "Now a string"

In [5]:
# Assigning Same Value: same value can be assigned to multiple variables in a single line.
a = b = c = 100
print(a, b, c)

100 100 100


In [6]:
# Assigning Different Values: Multiple variables can also be assigned different values in a single line.
x, y, z = 1, 2.5, "Python"
print(x, y, z)

1 2.5 Python


In [8]:
# Swapping Two Variables: Using multiple assignments, we can swap the values of two variables without needing a temporary variable.
a, b = 5, 10
a, b = b, a
print(b, a)

5 10


## Session Name :- Data Types || Date :- 05/08/2026

| Numerical | Sequential | Boolean|Set|Dictionary|
|-----------|------------|---------|---|----------|
| int| String| True|frozenset|
|float|List|False|
|complex|Tuple| 

- what is difference between set and fronzen set?

### Numerical Data type: 
1) int
2) float 
3) complex

In [10]:
# integer
a = 20
type(a)

int

In [11]:
b = 3.14
type(b)

float

In [12]:
c = 3+2j
type(c)

complex

### Sequencial data type:
1) string
2) list
3) tuple

#### String: 
1) It is denoted in ' ' or " ".
2) Immutable - we can not change it after creation 
3) indexed: []
 types: 1) Positive indexing ( left to right) index start with 0
          2) Negative indexing (right to left) index start with -1

Slicing: 
[start : end : step ]

In [24]:
var = "Python"
type(var)

str

In [25]:
len(var)

6

In [26]:
var = "Python"
var[0]

'P'

In [27]:
var[3]

'h'

In [28]:
var[-2]

'o'

In [29]:
var = "the joy of computing using PYTHON"
var[:]

'the joy of computing using PYTHON'

In [30]:
var = "the joy of computing using PYTHON"
var[1:]

'he joy of computing using PYTHON'

In [31]:
var = "the joy of computing using PYTHON"
var[:9]

'the joy o'

In [32]:
var = "the joy of computing using PYTHON"
var[3:9]

' joy o'

In [33]:
var = "the joy of computing using PYTHON"
var[ : : ]

'the joy of computing using PYTHON'

In [34]:
var = "the joy of computing using PYTHON"
var[::-1]

'NOHTYP gnisu gnitupmoc fo yoj eht'

In [35]:
var = "the joy of computing using PYTHON"
var[::-2]

'NHY ns ntpo oyjet'

In [36]:
var = "the joy of computing using PYTHON"
var[::-3]

'NT i ipcooe'

In [37]:
var = "the joy of computing using PYTHON"
var[1:9:-2]

''

In [38]:
var = "the joy of computing using PYTHON"
var[-2:-12:-2]

'OTPgi'

In [39]:
# Methods: String:
var = "the joy of computing using PYTHON"
var.capitalize()

'The joy of computing using python'

In [40]:
var = "the joy of computing using PYTHON"
var.casefold()

'the joy of computing using python'

In [41]:
var = "the joy of computing using PYTHON"
var.center(40,'*')

'***the joy of computing using PYTHON****'

In [42]:
var = "the joy of computing using PYTHON"
var.isupper()

False

In [43]:
var = "the joy of computing using PYTHON"
var.islower()

False

In [44]:
var = "the joy of computing using PYTHON"
var.upper()

'THE JOY OF COMPUTING USING PYTHON'

In [45]:
var = "the joy of computing using PYTHON"
var.lower()

'the joy of computing using python'

In [46]:
var = "the joy of computing using PYTHON"
var.startswith("THE")

False

In [47]:
var = "the joy of computing using PYTHON"
var.count('o')

3

In [48]:
var = "the joy of computing using PYTHON"
var.index('PYTHON')

27

In [49]:
var = "the joy of computing using PYTHON"
var.isalnum() # is alphabet numeric 

False

In [50]:
x = 'var123'
x.isalnum()

True

In [51]:
var = "the joy of,computing using PYTHON"
var.split(",")

['the joy of', 'computing using PYTHON']

In [52]:
var = "the joy of computing using PYTHON"
var.zfill(40)

'0000000the joy of computing using PYTHON'

#### List
1) list is a sequencial data type
2) indexed, duplicates allowed
3) Mutable - we can change it. 
4) It is denoted in []

In [53]:
l1 = [1,2,3,4,"Fusion","India","Success",4,3,2,1,True,3.14]
type(l1)

list

In [54]:
l1[4][3]

'i'

In [55]:
l1[::-2]

[3.14, 1, 3, 'Success', 'Fusion', 3, 1]

In [56]:
# mutable
l1 = [1,2,3,4,"Fusion","India","Success",4,3,2,1,True,3.14]
l1[5] = "Maharashtra"
l1

[1, 2, 3, 4, 'Fusion', 'Maharashtra', 'Success', 4, 3, 2, 1, True, 3.14]

In [57]:
#Methods:
l1 = [1,2,3,4,"Fusion","Progress"]
l1.append([11,12])
l1

[1, 2, 3, 4, 'Fusion', 'Progress', [11, 12]]

In [58]:
l1 = [1,2,3,4,"Fusion","India"]
l2 = [11,12]
l1.extend(l2)
l1

[1, 2, 3, 4, 'Fusion', 'India', 11, 12]

In [59]:
l1 = [1,2,3,4,"Fusion","India"]
l2 = l1.copy()
l2

[1, 2, 3, 4, 'Fusion', 'India']

In [60]:
l1 = [1,2,3,4,"Fusion","India"]
l1.count(4)

1

In [61]:
l1 = [1,2,3,4,"Fusion","India"]
l1.index(4)

3

In [62]:
l1 = [1,2,3,4,"Fusion","India"]
l1.insert(3,"MH")
l1

[1, 2, 3, 'MH', 4, 'Fusion', 'India']

In [63]:
l1 = [1,2,3,4,"Fusion","India"]
l1.pop()

'India'

In [64]:
l1

[1, 2, 3, 4, 'Fusion']

In [65]:
l1 = [1,2,3,4,"Fusion","India"]
l1.remove(3)
l1

[1, 2, 4, 'Fusion', 'India']

In [66]:
l1 = [1,2,3,4,"Fusion","India"]
l1.reverse()
l1

['India', 'Fusion', 4, 3, 2, 1]

In [67]:
l1 = [1,11,43,25,22,18]
l1.sort(reverse=True)
l1

[43, 25, 22, 18, 11, 1]

In [68]:
l1 = [1,2,3,4,"Fusion","India"]
l1.clear()
l1

[]

#### Tuple
1) it is a sequencial data type
2) indexed, duplicates allowed
3) immutable - we can not change it
4) parenthesis ()

In [69]:
var = (1,2,3,4,"India",True)
type(var)

tuple

In [70]:
len(var)

6

In [2]:
# immutable 
var = (1,2,3,4,"India",True)
print(var[4])

India


In [72]:
# methods:
var = (1,2,3,4,"India",True)
var.

SyntaxError: invalid syntax (296166589.py, line 3)

In [77]:
# methods:
var = (1,2,3,4,"India",True)
var.count(2)


1

In [76]:
var.index("India")

4

### Boolean :-
- True
- False

In [79]:
a = True
b = False
type(a)

bool

In [78]:
# Multiline commment:

''' 
There was a king....

'''

' \nThere was a king....\n\n'

### Dictionary: 
1) It is a key - value pair 
2) It is created using {}
3) ordered, indexing/slicing can not performed.
4) it is a mutable data type: we can change/modify it.

In [80]:
dict1 = {"First":"Python", "second":"C++", "third":"JAVA"}
print(type(dict1))

<class 'dict'>


In [81]:
dict1[0]

KeyError: 0

In [82]:
dict1

{'First': 'Python', 'second': 'C++', 'third': 'JAVA'}

In [83]:
# mutable
dict1 = {"First":"Python", "second":"C++", "third":"JAVA"}
dict1["second"] = "SQL"
dict1

{'First': 'Python', 'second': 'SQL', 'third': 'JAVA'}

In [84]:
# methods
dict1 = {"First":"Python", "second":"C++", "third":"JAVA"}
dict2 = dict1.copy() # copies the older dict

In [85]:
dict2

{'First': 'Python', 'second': 'C++', 'third': 'JAVA'}

In [86]:
dict1 = {"First":"Python", "second":"C++", "third":"JAVA"}
dict1.fromkeys("First") # it will create a seperate dict with splited charcter of key

{'F': None, 'i': None, 'r': None, 's': None, 't': None}

In [87]:
dict1 = {"First":"Python", "second":"C++", "third":"JAVA"}
dict1.get("second") # inorder to get value of the particular key

'C++'

In [88]:
dict1 = {"First":"Python", "second":"C++", "third":"JAVA"}
dict1.values()

dict_values(['Python', 'C++', 'JAVA'])

In [89]:
dict1 = {"First":"Python", "second":"C++", "third":"JAVA"}
dict1.keys()

dict_keys(['First', 'second', 'third'])

In [90]:
dict1 = {"First":"Python", "second":"C++", "third":"JAVA"}
dict1.items()

dict_items([('First', 'Python'), ('second', 'C++'), ('third', 'JAVA')])

In [91]:
dict1 = {"First":"Python", "second":"C++", "third":"JAVA"}
dict1.pop("third") # it is used to remove the specific key value pair
dict1

{'First': 'Python', 'second': 'C++'}

In [92]:
dict1 = {"First":"Python", "second":"C++", "third":"JAVA"}
dict1.popitem()
dict1

{'First': 'Python', 'second': 'C++'}

In [93]:
dict1 = {"First":"Python", "second":"C++", "third":"JAVA"}
dict1.setdefault("fourth")

In [94]:
dict1

{'First': 'Python', 'second': 'C++', 'third': 'JAVA', 'fourth': None}

In [95]:
dict1 = {"First":"Python", "second":"C++", "third":"JAVA"}
dict1.update({"fourth":"Pearl"})
dict1

{'First': 'Python', 'second': 'C++', 'third': 'JAVA', 'fourth': 'Pearl'}

In [96]:
dict1.clear()
dict1

{}

### Set 
1) It is denoted as {}
2) unorder . unindex , duplicated auto remove
3) mutable
4) mathematical operation are fast

In [97]:
set1 = {1,4,2,6,6,7}
set1

{1, 2, 4, 6, 7}

In [98]:
set1 = {1,4,2,6,6,7}
len(set1)

5

In [99]:
set1 = {1,4,2,6,6,7}
set1[0]

TypeError: 'set' object is not subscriptable

In [100]:
set1 = {1,4,2,6,6,7}
set1[0] = 11
set1

TypeError: 'set' object does not support item assignment

In [101]:
#methods
set1 = {1,2,3,4,5}
set2 = {4,5,6,7,8}
set3 = {7,8,9,10,11}
set4 = set1.union(set2)
set4.union(set3)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}

In [102]:
set1.intersection(set2)

{4, 5}

## Session Name :- Operators || Date :- 06/08/2026

### Operators

#### Arthmetic operator

In [2]:
a= 20
b = 7
print(f"Arthmetic {a+b}")
print(f"subtraction {a-b}")
print(f"multiplication {a*b}")
print(f"division {a/b}")
print(f"modulo {a%b}")
print(f"floor division {a//b}")
print(f"power {a**2}")

Arthmetic 27
subtraction 13
multiplication 140
division 2.857142857142857
modulo 6
floor division 2
power 400


#### comparison

In [3]:
a = 30
b = 15
a == b

False

In [4]:
a > b

True

In [5]:
a < b

False

In [6]:
a >= b 

True

In [7]:
a <= b 

False

In [8]:
a != b

True

#### Logical 

In [9]:
a = True
b = False

In [10]:
a or b

True

In [11]:
a and b

False

In [13]:
not b

True

#### Assingment

In [19]:
a = 10
b = 5

In [24]:
a = 10
b = 5
a += b
a

15

In [25]:
a = 10
b = 5
a -= b
a

5

In [26]:
a = 10
b = 5
a *= b
a

50

In [28]:
a = 10
b = 5
a /= b
a

2.0

In [29]:
a = 10
b = 5
a %= b 
a

0

In [30]:
a = 10
b = 5
a //= b
a

2

In [31]:
a = 10
b = 5
a **= b
a

100000

#### Membership

1) in
2) not in

In [33]:
l1 = [4,5,87,96,58,42,65]
a = 89
if a in l1 : print("inside")
else : print("not inside")

not inside


In [35]:
l1 = [4,5,87,96,58,42,65]
a = 89
if a not in l1 : print(" not inside")
else : print("inside")

 not inside


#### Identity
1) is
2) is not

In [36]:
a = 20
b = 10

In [37]:
a is b

False

In [38]:
a is not b

True

#### Bitwise

In [103]:
7 & 2

2

In [104]:
7 ^ 2

5

In [105]:
5 >> 2

1

In [106]:
5 << 2

20

## Session name :- Conditional Satement (if-elif-else) ||  Date :- 7/08/2026

In [1]:
age = int(input("Enter your age"))
if age > 18 :
    print("You are eligible for vote")
else:
    print("Your are not eligible for vote")

Enter your age 45


You are eligible for vote


In [7]:
n1,n2 = int(input("enter 1st no.")),int(input("enter 2nd no."))
if n1 >n2:
    print(f"{n1} is greater than {n2}")
else:
    print(f"{n2} is greater than {n1}")

enter 1st no. 12
enter 2nd no. 45


45 is greater than 12


In [4]:
n = int(input("Enter the number"))
if n%2==0 :
    print(f"The Number {n} is even")
else:
    print(f"The Number {n} is odd")

Enter the number 17


The Number 17 is odd


In [10]:
n = int(input("Enter the number"))
if n%5==0 :
    print(f"The Number {n} is divisible by 5")
else:
    print(f"The Number {n} is not divisible by 5")

Enter the number 25


The Number 25 is divisible by 5


In [16]:
age = int(input("Enter Your age"))
if age > 18 :
    print("Your are eligible for voting")
elif age == 0:
    print("Invalid input")
elif age < 0:
    print("Negative ages cannot exists")
else:
    print("You are not eligible for vote")

Enter Your age 24


Your are eligible for voting


In [38]:
n = int(input("Enter your age"))
if n % 2 != 0:
    print("Weird")
elif 2 <= n <=5:
    print("Not Weird")
elif 6 <= n <=20:
    print("Weird")
else :
    print("Not Weird")

Enter your age 4


Not Weird


In [41]:
a,b,c = int(input("Enter Your 1st number")),int(input("Enter Your 2nd Number")),int(input("Enter Your 3rd Number"))

if a>b and a>c:
    print(f"{a} is greater than {b} and {c}")
elif b>a and b>c:
    print(f"{b} is greater than {a} and {c}")
else:
    print(f"{c} is greater than {a} and {b}")

Enter Your 1st number 4
Enter Your 2nd Number 18
Enter Your 3rd Number 2


18 is greater than 4 and 2


## Session name :- Loops and Control Statement ||  Date :- 10/08/2026

what is difference between for loop and while loop

### Conditional Statements

- for loop
- while loop

#### For loop
 

In [ ]:
for i in range():
    statement

In [2]:
for i in range(1,11):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 

In [7]:
for i in range(10):
    print("Yash", end=" ")

Yash Yash Yash Yash Yash Yash Yash Yash Yash Yash 

In [6]:
print("Yash "*10)

Yash Yash Yash Yash Yash Yash Yash Yash Yash Yash 


In [8]:
for i in range(1,11):
    print(f"{21} * {i} = {21*i}")

21 * 1 = 21
21 * 2 = 42
21 * 3 = 63
21 * 4 = 84
21 * 5 = 105
21 * 6 = 126
21 * 7 = 147
21 * 8 = 168
21 * 9 = 189
21 * 10 = 210


In [10]:
num = int(input("Enter Number"))
for i in range(1,11):
    print(f"{num} * {i} = {num*i}")

Enter Number 25


25 * 1 = 25
25 * 2 = 50
25 * 3 = 75
25 * 4 = 100
25 * 5 = 125
25 * 6 = 150
25 * 7 = 175
25 * 8 = 200
25 * 9 = 225
25 * 10 = 250


#### While loop

In [14]:
i=1
while i < 11:
    print(i,end=" ")
    i+=1

1 2 3 4 5 6 7 8 9 10 

In [15]:
i=1
while i < 51:
    print(i,end=" ")
    i+=1

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 

In [16]:
i=1
while i <= 10:
    print(f"{25} * {i} = {25*i}")
    i+=1

25 * 1 = 25
25 * 2 = 50
25 * 3 = 75
25 * 4 = 100
25 * 5 = 125
25 * 6 = 150
25 * 7 = 175
25 * 8 = 200
25 * 9 = 225
25 * 10 = 250


### Control Statement

- break
- continue
- pass

In [18]:
#break
i=1
while i < 51:
    print(i,end=" ")
    i+=1
    if i == 25:
        break

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 

In [28]:
#continue
i=0
while i < 50:
    i+=1
    if i == 25:
        continue
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 

In [25]:
#pass
i=0
while i < 51:
    i+=1
    if i == 25:
        pass
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 

## Session name :- Programs ||  Date :- 11/08/2026

In [1]:
#write the python program to print length of the input given by user
str1 = input("Enter the string")
count=0
for i in str1:
    count+=1
print(f"The lenght of {str1} is {count}")

Enter the string google


The lenght of google is 6


In [3]:
#take a list add some numbers and find out sum of all elements in a list
l1 = [1,23,43,23,56]
sum1 =0
for i in l1 :
    sum1+=i
print(sum1)

146


In [6]:
#Take a list and add some value -ve and +ve print count of -ve terms
l2=[12,43,-9,25,-34,-45]
count=0
for i in l2:
    if i < 0:
        count+=1
print(f"Negative numbers {count}")

Negative numbers 3


In [7]:
# maximum number from list
l1=[12,87,90,56,-999,999]
max1 = 0
for i in l1:
    if max1 < i:
        max1 = i
print(f"The maximum number from list is {max1}")

The maximum number from list is 999


In [ ]:
max_n = float("-inf") #- infinite
min_n = float("inf") # + infinite

In [9]:
# minimum number from list
l1=[12,87,90,56,-999,999]
min1 = 0
for i in l1:
    if min1 > i:
        min1 = i
print(f"The Minimun number from list is {min1}")

The maximum number from list is -999


In [20]:
l1 = ["India", "Austrelia","London","Singapore"]
l2 = l1[0]

for i in l1:
    if len(i)>len(l2):
        l2=i
print(l2)
type(l2)

Austrelia


str

In [30]:
#palindrome
string = input("Enter the string to check for palindrome ")
reverse=""
for i in range(len(string)-1,-1,-1):
    reverse += string[i]
if reverse == string:
    print("The string is palindrome")
else:
    print("The string is not palindrome")

Enter the string to check for palindrome  baye


The string is not palindrome


In [31]:
#1) write a python program to count number of charcters(charcter frequency in string) ex. google then g-2 o- 2 l-1 e-1
#2)  write a python program to check palindrome number without converting into string
# 3) write a python program to remove duplicate characters from string
# 4) write a python program to remove duplicate number from list
#5)  take an empty list add some va;ue into that which will come from user and sorted it in descending order

In [18]:
# 1) write a python program to count number of charcters(charcter frequency in string)
user = input("Enter the String")
char_count = {}
for char in user:
    if char in char_count:
        char_count[char] += 1
    else:
        char_count[char] = 1
        
print(char_count)

Enter the String google


{'g': 2, 'o': 2, 'l': 1, 'e': 1}


In [6]:
#2)  write a python program to check palindrome number without converting into string
num = int(input("Enter the number "))
reverse = 0
while num > 0:
    digit = num%10
    reverse = reverse * 10 + digit
    num = num//10

if reverse == num :
    print("the number is palindrome")
else:
    print("The number is not palindrome")

Enter the number  123456


The number is not palindrome


In [20]:
#3) write a python program to remove duplicate characters from string
str1 =input("Enter the string")
b = ""
for char in str1:
    if char not in b:
        b += char
print(b)

Enter the string google


gole


In [10]:
# 4) write a python program to remove duplicate number from list
num = [1,2,3,4,5,5,7,8,7,8,9,4,5,7,8,1,0,45,7,48]
unique = []
for i in num:
    if i not in unique:
        unique.append(i)
print(unique)

[1, 2, 3, 4, 5, 7, 8, 9, 0, 45, 48]


In [11]:
# 4) write a python program to remove duplicate number from list
num = [1,2,3,4,5,5,7,8,7,8,9,4,5,7,8,1,0,45,7,48]
unique = list(set(num))
print(unique)

[0, 1, 2, 3, 4, 5, 7, 8, 9, 45, 48]


In [15]:
#5)  take an empty list add some value into that which will come from user and sorted it in descending order
l1 =[]
for i in range(10) :
    user = int(input("Enter the number"))
    l1.append(user)

l1.sort(reverse="True")
print(l1)

Enter the number 9
Enter the number 8
Enter the number 7
Enter the number 5
Enter the number 2
Enter the number 1
Enter the number 7
Enter the number 6
Enter the number 2
Enter the number 4


[9, 8, 7, 7, 6, 5, 4, 2, 2, 1]


## Session name :- Functions ||  Date :- 12/08/2026

### Function 
- It is block of code which perform specific task and help organize code , reuse code.

Types
1) Built-in Function
2) user define function 
3) Anonymous Fuction(lambda function)
4) Recursive Fuction

### Difference Between Parameter and Argument

| **Parameter** | **Argument** |
|---|---|
| Variable defined in the function definition | Actual value passed to the function |
| Acts as a **placeholder** | Provides the actual data |
| Defined when creating the function | Passed when calling the function |
| Receives the value | Sends the value |
| Example: `name` | Example: `"Mayur"` |
| Example: `def greet(name):` | Example: `greet("Mayur")` |
| Parameters exist inside the function definition | Arguments exist in the function call |

- Parameter = a variable/placeholder written in the function definition.
- Argument = the actual value you give to the function when calling it
- Parameter = receives the value
- Argument = gives the value
  
### Difference Between `return` and `print()`

| `return` | `print()` |
|---|---|
| Sends a value back from a function. | Displays a value on the screen/console. |
| Used inside a function. | Can be used inside or outside a function. |
| The returned value can be stored in a variable. | The displayed value cannot be directly stored as the output of `print()`. |
| Ends the function execution. | Does not end the function execution. |
| Mainly used when the result needs to be used later. | Mainly used when you want to show information to the user. |
| `return` is a Python keyword. | `print()` is a built-in Python function. |
| Example: `return result` | Example: `print(result)` |

- return → Gives a value back from a function.
- print() → Shows a value on the screen.

#### User define function 

In [1]:
#syntac of fuction defination
def fuction_name(parameter):
    "Doctstring"
    #a fuction body
    return expression

In [4]:
def Calculator(a,b) : #(Parameters)
    print(f"Addition {a+b}")
    print(f"Substraction {a-b}")
    print(f"Multiplication {a*b}")
    print(f"Division {a/b}")

In [5]:
#fuction Calling
Calculator(10,7) #Arguments

Addition 17
Substraction 3
Multiplication 70
Division 1.4285714285714286


In [11]:
def maximum(a,b):
    if a>b:
        print(f"{a} is grater than {b}")
    else:
        print(f"{b} is greater than {a}")


a,b = int(input("Enter the 1st Number")),int(input("Enter the 2nd number"))

maximum(a,b)

Enter the 1st number 45
Enter the 2nd number 68


68 is greater than 45


In [10]:
#create a python program to check umber is odd or even using function
def odd_even(a):
    if a%2 == 0:
        print(f"{a} is even")
    else:
        print(f"{a} is odd")

a = int(input("Enter the number"))
odd_even(a)

Enter the number 21876498


21876498 is even


In [12]:
#return
def add(a,b):
    return a+b
result = add(10,20)
print(result)

30


In [13]:
#print
def add(a,b):
    print(a+b)
result = add(10,20)
print(result)

30
None


#### Types of Arguments

1) Positional arguments
2) Keyword Arguments

#### Positional Argument
- In positional arguments, values are assigned to parameters based on their position/order

In [15]:
def student(name,age,course):
    print(f"Name : {name}")
    print(f"Age : {age}")
    print(f"Course : {course}")

student("Rahul",22,"Data Science")

Name : Rahul
Age : 22
Course : Data Science


#### Python `*args` and `**kwargs`

#### What is `*args`?

- The `*args` parameter allows a function to accept any number of positional arguments.
- Inside the function, `args` becomes a tuple containing all the passed arguments.


In [20]:
def rank(*args):
    return args[0] + args[1]

In [21]:
rank("Sachine"," Harshal","Pallavi","Harsh","Sanchita")

'Sachine Harshal'

#### Keywords Arguments
- In keyword arguments, values are assigned to parameters based on their parameter names.

In [23]:
def rank(first,second,third):
    return first,second
rank(second="Harshal",first="Sachine",third="Pallavi")

('Sachine', 'Harshal')

#### Arbitrary Keyword Arguments - `**kwargs`

- If you do not know how many keyword arguments will be passed into your function, add two asterisks `**` before the parameter name.
- This way, the function will receive a dictionary of arguments and can access the items accordingly.

In [28]:
def rank(**kwargs):
    return kwargs
rank(name="yash",age=25,course="data science")

{'name': 'yash', 'age': 25, 'course': 'data science'}

## Session name :- Functions ||  Date :- 13/08/2026

### What is Local and Global Variable

#### Local Variable
- Local variables are defined inside a function and exist only during its execution.
- They cannot be accessed from outside the function.

In [4]:
def display():
    x=10 #local variable
    print(x)
display()

10


#### Global Variable

- A global variable is a variable that is created outside a function. It can be accessed from anywhere in the program.

In [3]:
x = 10 #global variable
def display():
    print(x)
display()

10


#### Global Keyword

- The `global` keyword is used when we want to modify a global variable inside a function.

In [9]:
x = 10
def change():
    global x
    x = 20

change()
print(x)

20


#### Lambda Fuction
- It is single line fuction
- A lambda is a small anonymous function defined using the `lambda` keyword.
- It can have any number of arguments but only one expression

In [10]:
#syntax
lambda arguments: expression

<function __main__.<lambda>(arguments)>

In [11]:
Max = lambda n1,n2: print(f"{n1} is greater than {n2}") if n1>n2 else print(f"{n2} is greater than {n1}")

In [12]:
Max(65,78)

78 is greater than 65


In [21]:
#write a python program to check whether given number is odd or even
odd_even = lambda a: "even" if a%2==0 else "odd"
odd_even(int(input("Enter the Number")))

Enter the Number 46


'even'

In [ ]:
# prime numbers


### Higher-Order Functions

- A higher-order function takes another function as an argument, returns one, or both.
- They are commonly used with Python's functional-style tools.

#### `map()`

- Applies a given function to all items in an input list and returns a map object (an iterator).

In [24]:
num = [2,4,5,8,7,9,5,4,2,6,1]
var = list(map(lambda x : x**2,num))
var

[4, 16, 25, 64, 49, 81, 25, 16, 4, 36, 1]

In [29]:
n1 = [1,2,3,4,5]
n2 = [6,7,8,9,10]
Sum = list(map(lambda a,b:a+b,n1,n2))
Sum

[7, 9, 11, 13, 15]

#### `filter()`

- The `filter()` function is used to filter elements from an iterable based on a condition.
- It returns an iterator containing only the elements for which the function returns `True`.


In [30]:
l1 = [4,5,78,1,2,34,2,45,5]
grt = list(filter(lambda x : x>4,l1))
grt

[5, 78, 34, 45, 5]

#### Recursive Fuction
- A function which calls it's self within a function is called Recursive

In [37]:
#factorial
def factorial(n):
    if n<0:
        return "Factorial Doesn't exist"
    elif n==0:
        return 1
    elif n == 1:
        return n
    else:
        return n * factorial(n-1)
n = int(input("Enter the number"))
factorial(n)

Enter the number 5


120

In [44]:
n = int(input("Enter the Number"))
a = 0
b = 1
for i in range(n):
    print(a,end=" ")
    a , b = b , a+b

Enter the Number 8


0 1 1 2 3 5 8 13 

## Session name :- Modules and Packages ||  Date :- 17/08/2026

#### Modules
- A module is simply a .py file which containg python code-fuctions, classes, or variabls-that you can reuse in other programs

In [1]:
import mymath

mymath.add(2,5)

7

In [2]:
mymath.squares(2)

4

##### Different ways to import module
- import module
- from module import name
- import module as alias Ex: import pandas as pd
- from module import *

#### Package
- It is directory of related modules that includes that a special file,"" __init__.py "" which tells python to treat the folder as importable package

In [10]:
from Fusion.circle import *
from Fusion.square import *

area(4)

50.26548245743669

In [11]:
square_area(4)

16

## Session name :- File Handling and Exception Handling ||  Date :- 18/08/2026

### File Hnadling
- Allow us to store data in permenetly in non volatile storage
- File operation :- read, write, update

  
1) Why File Handling
- Data Persistence
- Logging info
- Data Processing
- Configuration

#### Open File

In [1]:
file = open("sample.txt",'r')
var = file.read()
print(var)
file.close()

Hello this is sample file


In [ ]:
There are 3 methods
1) read()
2) readline()
3) readlines()

In [6]:
file = open("sample.txt",'r')
var = file.readline()
print(var)
file.close()

Hello this is override statement



In [7]:
file = open("sample.txt",'r')
var = file.readlines()
print(var)
file.close()

['Hello this is override statement\n', ' This is append statement']


#### Write File

In [2]:
file = open("sample.txt","w")
file.write("Hello this is override statement")
file.close()

In [3]:
file = open("sample.txt",'r')
var = file.read()
print(var)
file.close()

Hello this is override statement


#### Append File

In [4]:
file = open("sample.txt","a")
file.write("\n This is append statement")
file.close()

In [5]:
file = open("sample.txt",'r')
var = file.read()
print(var)
file.close()

Hello this is override statement
 This is append statement


### Exception Handling
1) try
2) except
3) else
4) finally

In [11]:
try:
    a= 10/0
except ZeroDivisionError :
    print("Cannot divide by zero")
else:
    print("Entre the valid number")
finally :
    print("succefully !!!!")

Cannot divide by zero
succefully !!!!


## Session name :- OOPs ||  Date :- 19/08/2026

1) class :- blueprint of objects / collection of object
2) object :- Instance of class
3) Inheritance :- Transfer of properties 1) Single 2) Multilevel 3) Multiple 4) Hierachical 5) Hybrid
4) Polymorphism
5) Abstraction
6) Encapsulation

In [5]:
class Arithmetic():
    def add(self,a,b):
        return a+b
    def sub(self,a,b):
        return a-b
obj = Arithmetic()
print(obj.add(20,7))
print(obj.sub(20,7))

27
13


In [9]:
class University:
    def college_name(self):
        print("PREC ,Loni")
    def depart_name(self):
        print("Computer Engineering")
clg = University()
clg.college_name()
clg.depart_name()

PREC ,Loni
Computer Engineering


In [10]:
#class by using constructor
__init__ 

In [11]:
class University:
    def __init__(self,cname,dname):
        self.cname = cname
        self.dname = dname
    def show(self):
        return "my college and Dept name is", self.cname , self.dname

obj = University("PREC","Computer")
print(obj.show())

obj1 = University("PVP","IT")
print(obj1.show())

('my college and Dept name is', 'PREC', 'Computer')
('my college and Dept name is', 'PVP', 'IT')


In [17]:
class Student:
    def __init__(self,name,age,course,marks):
        self.nm = name
        self.ag = age
        self.cs = course
        self.mk = marks
        
    def details(self):
        print(f"Student name:{self.nm} , Age :- {self.ag} , Course :{self.cs}, Marks: {self.mk} ")
        
    def result(self):
        if self.mk > 50:
            print(f"{self.nm} is Pass")
        else:
            print(f"{self.nm} is Fail")

stud1 = Student("Yash",22,"Data SCience",65)
stud2 = Student("Abhi",22,"Data Science",15)

stud1.details()
stud1.result()
print()
stud2.details()
stud2.result()

Student name:Yash , Age :- 22 , Course :Data SCience, Marks: 65 
Yash is Pass

Student name:Abhi , Age :- 22 , Course :Data Science, Marks: 15 
Abhi is Fail


In [2]:
#single Inheritance
class P:
    def __init__(self):
        print("Parent")
class B(P):
    def __init__(self):
        super().__init__()
        print("Child")
obj = B()

Parent
Child


In [7]:
class Parent:
    def __init__(self,fun1):
        self.fun1 = fun1
    def show(self):
        return self.fun1
class Child(Parent):
    def __init__(self,fun2,fun1):
        self.fun2 = fun2
        self.fun1 = fun1
    def show1(self):
        return self.fun2

obj = Child("This is a base class","This is a child class")
print(obj.show())
print(obj.show1())

This is a child class
This is a base class


In [10]:
class Employee:
    def __init__(self,ename,eid,edept,esalary):
        self.nm = ename
        self.id = eid
        self.dept = edept
        self.sal = esalary
    def employee_details(self):
        print(f"The Employee Name : {self.nm} , Employee Id :{self.id}, Employee Department :{self.dept}, Employee Salary: {self.sal} per Month")

e1 = Employee("Rahul",101,"HR",50000)
e2 = Employee("Rohit",102,"Finance",80000)
e3 = Employee("Ramesh",103,"Marketing",60000)

e1.employee_details()
e2.employee_details()
e3.employee_details()

The Employee Name : Rahul , Employee Id :101, Employee Department :HR, Employee Salary: 50000 per Month
The Employee Name : Rohit , Employee Id :102, Employee Department :Finance, Employee Salary: 80000 per Month
The Employee Name : Ramesh , Employee Id :103, Employee Department :Marketing, Employee Salary: 60000 per Month


In [11]:
class BankAccount:
    def __init__(self, aname, aid, atype, abalance):
        self.name = aname
        self.id = aid
        self.type = atype
        self.balance = abalance

    def account_details(self):
        print(f"Account Holder Name: {self.name}, Account Number: {self.id}, Account Type: {self.type}, Balance: {self.balance} per Month")


a1 = BankAccount("Rahul", 1001, "Savings", 50000)
a2 = BankAccount("Priya", 1002, "Current", 80000)
a3 = BankAccount("Amit", 1003, "Savings", 35000)

a1.account_details()
a2.account_details()
a3.account_details()

Account Holder Name: Rahul, Account Number: 1001, Account Type: Savings, Balance: 50000 per Month
Account Holder Name: Priya, Account Number: 1002, Account Type: Current, Balance: 80000 per Month
Account Holder Name: Amit, Account Number: 1003, Account Type: Savings, Balance: 35000 per Month


In [12]:
class Patient:
    def __init__(self, pname, pid, pdisease, pdoctor, proom):
        self.name = pname
        self.id = pid
        self.disease = pdisease
        self.doctor = pdoctor
        self.room = proom

    def patient_details(self):
        print(f"Patient Name: {self.name}, Patient Id: {self.id}, Disease: {self.disease}, Doctor: {self.doctor}, Room Number: {self.room}")


p1 = Patient("Rahul", 201, "Fever", "Dr. Sharma", 101)
p2 = Patient("Priya", 202, "Diabetes", "Dr. Mehta", 102)
p3 = Patient("Amit", 203, "Migraine", "Dr. Singh", 103)

p1.patient_details()
p2.patient_details()
p3.patient_details()

Patient Name: Rahul, Patient Id: 201, Disease: Fever, Doctor: Dr. Sharma, Room Number: 101
Patient Name: Priya, Patient Id: 202, Disease: Diabetes, Doctor: Dr. Mehta, Room Number: 102
Patient Name: Amit, Patient Id: 203, Disease: Migraine, Doctor: Dr. Singh, Room Number: 103


## Session name :- OOPs ||  Date :- 20/08/2026

In [14]:
class Hospital:
    def __init__(self,pname,disease,age):
        self.nm = pname
        self.dis = disease
        self.ag = age
    def show(self):
        print(f"Patient Name :- {self.nm} , Disease is {self.dis}, Age is {self.ag}")

class Medical(Hospital):
    def __init__(self,medicines,pname,disease,age):
        self.med = medicines
        super().__init__(pname,disease,age)
        
    def show(self):
        super().show()
        print(f"Medicines provided by Hospital is : {self.med}")

p1 = Medical("Para","Saurav","Fever",45)
p1.show()

Patient Name :- Saurav , Disease is Fever, Age is 45
Medicines provided by Hospital is : Para


In [15]:
#multiple inhertnce
class B1:
    def fun1(self):
        print("This is base class 1")
class B2:
    def fun2(self):
        print("This is base class 2")
class C1(B1,B2):
    def fun3(self):
        super().fun1()
        super().fun2()
        print("This is derived class")

c1 = C1()
c1.fun3()

This is base class 1
This is base class 2
This is derived class


In [19]:
#mutilevel
class B:
    def fun1(self):
        print("This is Base class")
class C1(B):
    def fun2(self):
        print("This is Derived class 1")
class C2(C1):
    def fun3(self):
        super().fun1()
        super().fun2()
        print("This is derived class from C1")

obj = C2()
obj.fun3()

This is Base class
This is Derived class 1
This is derived class from C1


In [29]:
#polymorphism
class Arithmetic:
    def add(self,a,b):
        return a+b
    def add(self,a,b,c=0):
        return a+b+c
        
obj=Arithmetic()
print(obj.add(2,3,6))
print(obj.add(2,3,4))

#print(obj.add("ghi","jhl","fsk"))

11
9


In [7]:
#hybrid
class B1:
    def fun1(self):
        print("This is class A")
class C1(B1):
    def fun2(self):
        print("This is class C1")
class B2:
    def fun3(self):
        print("This is class B2")
class C2(B2,C1):
    def fun4(self):
        print("This is class C2")
class C3(C2):
    def fun5(self):
        print("This is class C3")

c1 = C3()
c1.fun1()
c1.fun2()
c1.fun3()
c1.fun4()
c1.fun5()

This is class A
This is class C1
This is class B2
This is class C2
This is class C3


In [3]:
class Car:
    def showroom(self):
        print("Showroom name is ABC")
    def showroom(self,location=''):
        print("Location of the showroom is",location)
    def showroom(self,location='',owner=''):
        print("Location and ownser of the showroom is",location, owner)
obj = Car()
obj.showroom("Pune-Kharadi")

Location and ownser of the showroom is Pune-Kharadi 


In [4]:
# method of over-riding
# diff class having same methods but diff number of parameter
class A:
    def fun(self):
        print("This is function 1")
    def fun(self):
        print("this is function 2")
class B(A):
    def fun(self):
        print("THis is function 3")
    def fun(self,location=''):
        print("This is function 4")

obj = B()
obj.fun("MUMBAI")

This is function 4


## Session name :- Practice ||  Date :- 21/08/2026

### Fronzen set
- It is immutable version of set (cannot be change)

In [8]:
var = frozenset([1,2,3,4])
type(var)

frozenset

### Shallow copy
A shallow copy creates  a new outer object, but nested(inner) object are shared between original and copied object
- Outer obj -> new
- Inner Obj -> Shared(same memory reference)

In [11]:
l1 = [1,2,3]
l2 = l1
l2[0] = 100
print(f"L1 {l1}")
print(f" L2 {l2}")

L1 [100, 2, 3]
 L2 [100, 2, 3]


In [12]:
# shalow copy
import copy
l1 = [1,2,3]
l2 = copy.copy(l1)
l2[0]=100
print(f"Original List :{l1}")
print(f"Copied List :{l2}")

Original List :[1, 2, 3]
Copied List :[100, 2, 3]


#### Nested List

In [14]:
# shalow copy
import copy
l1 = [1,2,3,[20,30]]
l2 = copy.copy(l1)
l2[3][0]=999
print(f"Original List :{l1}")
print(f"Copied List :{l2}")

Original List :[1, 2, 3, [999, 30]]
Copied List :[1, 2, 3, [999, 30]]


### Deep Copy
A deep copy creates independent copy of the original object,including all nested objects

In [17]:
# Deep copy
from copy import deepcopy

l1 = [1,2,3,[20,30]]
l2 = deepcopy(l1)

l2[3][0]=999

print(f"Original List :{l1}")
print(f"Copied List :{l2}")

Original List :[1, 2, 3, [20, 30]]
Copied List :[1, 2, 3, [999, 30]]


### List Comprehension


In [21]:
#BASIC
sq = [num **2 for num in range(10)]
sq

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [22]:
# list comprehension with  condition
l1 = [n for n in range(25) if n%2==0]
l1

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]

In [26]:
# List comprehension with iterable
list1 = [1,2,3]
list2=['ab','bc','cd']

pair = [[i,j] for i in list1 for j in list2]
print(pair)

[[1, 'ab'], [1, 'bc'], [1, 'cd'], [2, 'ab'], [2, 'bc'], [2, 'cd'], [3, 'ab'], [3, 'bc'], [3, 'cd']]


### Iterator
- Iterators are advance python concept that allow for efficient looping ad memory management. Iterators provide a way to acces elements of collection sequentially without exposing the underlying structure

In [5]:
lst = [1,2,3,4,5,6]
for i in lst:
    print(i)

1
2
3
4
5
6


type(lst)

In [6]:
#Iterator

In [7]:
iterator=iter(lst)
type(iterator)

list_iterator

In [8]:
iterator

In [9]:
next(iterator)

1

### Genetaors
- Generators are simpler way to create iterators.They use the yeild keywords to produc a series of values lazily which means they geneate values on fly and do not store them in memory

In [45]:
def cube(n):
    for i in range(3):
       yield i**3

cube(3)

<generator object cube at 0x0000027E1F865E50>

### Decorators
- Decorators are powerful and flexible feature in python that allow yo to modify the behavior of function or class method. The are commonly used to add functionality to functions or methods without modifying their actual code

In [46]:
#Decoretor
def my_decorator(func):
    def wrapper():
        print("Something happen before the function is callde")
        func()
        print("Something is happend after the function is callde")
    return wrapper

In [47]:
@my_decorator
def say_hello():
    print("Hello !")

In [48]:
say_hello()

Something happen before the function is callde
Hello !
Something is happend after the function is callde


## Session name :- Numpy ||  Date :- 24/08/2026

- NumPy is the fundamental Python library for fast numerical and scientific computing. It provides powerful multidimensional arrays and efficient mathematical operations.

whats is difference between concate merge join

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
np.__version__

'2.5.1'

#### Python Array vs NumPy Array

In [4]:
#array using python
import array as arr
a = arr.array('i',[1,2,3,4])
type(a)

array.array

In [2]:
#array using numpy
import numpy as np
n = np.array([1,2,3,4,5])
type(n)

numpy.ndarray

### Types of NumPy Arrays
**Definition:** NumPy arrays can have different dimensions. A 1D array behaves like a vector, a 2D array like a matrix, and higher-dimensional arrays can represent stacked or tensor-like data.

#### 1D Array

**Definition:** A one-dimensional array contains values along a single axis and is commonly used for sequential numerical data.


In [6]:
#1D array
l1 = [1,2,3,4,5]
n1 = np.array(l1)
type(n1)

numpy.ndarray

In [7]:
n1.ndim

1

#### 2D Array

**Definition:** A two-dimensional array contains rows and columns and is commonly used for matrices and tabular numerical structures.


In [8]:
#2D array
n2 = np.array([[1,2],[3,4]])
n2

array([[1, 2],
       [3, 4]])

In [9]:
n2.ndim

2

In [14]:
n2.shape

(2, 2)

In [15]:
n2[0][0]

np.int64(1)

#### 3D Array

**Definition:** A three-dimensional array adds another axis and can represent multiple 2D matrices or tensor-like data.


In [11]:
#3D array
n3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
n3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [12]:
n3.ndim

3

In [13]:
n3.shape

(1, 3, 3)

In [16]:
n3.dtype

dtype('int64')

### NumPy Array Attributes

**Definition:** Array attributes describe the structure and data stored inside an ndarray.

#### ndim, shape, size and dtype

**Definition:** ndim gives the number of dimensions, shape gives the size of each dimension, size gives the total number of elements, and dtype gives the element data type.

In [3]:
a = np.array([[10, 20], [30, 40]])

print(a.ndim)   # Dimensions
print(a.shape)  # Shape tuple
print(a.size)   # Element count
print(a.dtype)  # Data type

2
(2, 2)
4
int64


### Creating Special Arrays

**Definition:** NumPy provides functions for quickly creating arrays filled with zeros, ones, a constant value, or identity-matrix values.


#### Zeros Array

**Definition:** np.zeros() creates an array filled with zeros.

In [5]:
# zeros
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### Ones Array

**Definition:** np.ones() creates an array filled with ones.


In [8]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Identity Matrix

**Definition:** np.eye() creates a matrix with ones on the main diagonal and zeros elsewhere.


In [7]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Full Array

**Definition:** np.full() creates an array of a specified shape filled with one chosen value.


In [6]:
np.full((3,3),20)

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

### Creating Sequences

**Definition:** NumPy can generate numerical sequences using functions such as arange() and linspace().


#### np.arange()

**Definition:** np.arange() generates evenly spaced values over a half-open interval, with an optional step.


In [25]:
#arange
a = np.arange(1,100)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
b = np.arange(1,100,5)
b

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

#### np.linspace()

**Definition:** np.linspace() generates a specified number of evenly spaced values between a start and end value, including the endpoint by default.


In [31]:
c = np.linspace(0,10,4)
c

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

### Random Module

**Definition:** NumPy's random submodule generates pseudo-random numbers, integers, and multidimensional arrays for simulations and experiments.


#### Random Floating-Point Numbers

**Definition:** np.random.rand() generates random floating-point values in the interval from 0.0 up to but not including 1.0.


In [10]:
# random
n = np.random.rand(3)
n

array([0.4458812 , 0.91578175, 0.52886898])

#### Random Integers

**Definition:** np.random.randint() generates random integers from the lower bound up to but excluding the upper bound.


In [11]:
a = np.random.randint(1,100,1)
a

array([28], dtype=int32)

#### Random Matrix

**Definition:** np.random.rand() can create a multidimensional array when row and column dimensions are supplied.


In [12]:
np.random.rand(3,3)

array([[0.6955727 , 0.11648434, 0.95033985],
       [0.20663249, 0.25129565, 0.29433759],
       [0.86929104, 0.58754182, 0.78973544]])

### Array Indexing & Slicing

**Definition:** Indexing selects individual array elements, while slicing selects a range or subset of elements.


#### 1D and 2D Indexing/Slicing

**Definition:** NumPy uses zero-based indexing; multidimensional arrays use one index per axis, and slicing follows the start:stop:step pattern.


In [17]:
# indexing and slicing

n2 = np.array([[1,2,3],[4,5,6]])
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
n2[1][2]

np.int64(6)

In [19]:
n2[:][0:1]

array([[1, 2, 3]])

In [20]:
a = np.array([10, 20, 30, 40, 50])

print(a[0])    # First element
print(a[-1])   # Last element
print(a[1:4])  # Indices 1 to 3
print(a[::2])  # Every second element


10
50
[20 30 40]
[10 30 50]


In [21]:
a = np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])

print(a[0, 1])  # Row 0, Column 1
print(a[2, 2])  # Row 2, Column 2
print(a[:, 1])  # All rows, Column 1
print(a[1, :])  # Row 1, All columns


20
90
[20 50 80]
[40 50 60]


### Data Types

**Definition:** NumPy arrays store elements using a defined data type, which can be specified when creating an array or changed later with astype().


#### Specify and Convert Data Types

**Definition:** The dtype parameter specifies the type during array creation, while astype() converts an existing array to another type.

- astype() does not change the dtype of the original array. It creates and returns a new array with the requested dtype.


In [23]:
#converting the Type of array
n1 = np.array([1,2,3,4,5],dtype='float')
n1.dtype

dtype('float64')

In [32]:
n2 = n1.astype(int)
n2

array([1, 2, 3, 4, 5])

In [33]:
n2.dtype

dtype('int64')

In [34]:
# Common NumPy data types:
# int     -> integer values
# float   -> floating-point values
# bool    -> True / False
# complex -> real + imaginary values

### Arithmetic Operations

**Definition:** NumPy performs element-wise arithmetic directly on arrays with compatible shapes.


#### Addition, Subtraction, Multiplication and Division

**Definition:** The operators +, -, *, and / apply arithmetic element-by-element between compatible arrays.


In [35]:
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

n1 + n2

array([50, 70, 90])

In [36]:
n1 - n2

array([-30, -30, -30])

In [37]:
n1 * n2

array([ 400, 1000, 1800])

In [38]:
n1 / n2

array([0.25, 0.4 , 0.5 ])

### Mathematical Functions

**Definition:** NumPy provides vectorized mathematical functions that operate efficiently on every element of an array.


#### Square Root

**Definition:** np.sqrt() calculates the square root of each array element.


In [39]:
a = np.array([1,4,9,16])
np.sqrt(a)

array([1., 2., 3., 4.])

#### Power

**Definition:** np.power() raises each element to a specified exponent.


In [40]:
a = np.array([1,4,9,16])
np.power(a,3)

array([   1,   64,  729, 4096])

#### Logarithm

**Definition:** np.log() calculates the natural logarithm of each element.


In [41]:
a = np.array([1,4,9,16])
np.log(a)

array([0.        , 1.38629436, 2.19722458, 2.77258872])

#### Trigonometric Functions

**Definition:** Functions such as np.sin() and np.cos() calculate trigonometric values element-wise.


In [42]:
a = np.array([0,90,180,260])
np.sin(a)

array([ 0.        ,  0.89399666, -0.80115264,  0.6832397 ])

In [43]:
a = np.array([0, 1, 2, 3])
np.cos(a)


array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])

### Aggregation and Statistics

**Definition:** Aggregation functions reduce an array to summary values such as mean, minimum, maximum, variance, and standard deviation.


#### Generating Data for Statistics

**Definition:** A numerical sequence or random array can be used as a dataset for statistical calculations.


In [44]:
b1 = np.arange(1,1000,50)
b1

array([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601,
       651, 701, 751, 801, 851, 901, 951])

In [45]:
c1 = np.random.randint(1,1000,50)

In [46]:
c1

array([ 39, 112,  49, 820, 180, 727, 392, 489, 127,  70, 731, 476, 170,
       616,  48, 489, 460, 448, 892, 147, 596, 155, 113, 318,   2, 791,
       726, 461, 143, 745, 823, 886, 505, 707,  88, 581, 636, 923, 588,
       852, 382, 915, 344, 225, 760,  35, 523, 508, 846, 332], dtype=int32)

#### Mean, Maximum and Minimum

**Definition:** Mean gives the average, while maximum and minimum give the largest and smallest values.


In [47]:
np.mean(c1)

np.float64(459.82)

In [48]:
np.max(c1)

np.int32(923)

In [49]:
np.min(c1)

np.int32(2)

In [50]:
a = np.array([10,20,30,40,50])

print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))
print(np.var(a))


150
30.0
10
50
14.142135623730951
200.0


### Matrix Operations

**Definition:** NumPy supports matrix addition, subtraction, multiplication, and transpose operations on multidimensional arrays.


#### Matrix Creation and Addition

**Definition:** Matrices can be represented as 2D NumPy arrays and added element-wise.


In [51]:
m1 = np.array([[1,2],[3,4]])
m1

array([[1, 2],
       [3, 4]])

In [52]:
m2 = np.array([[1,2],[3,4]])
m2

array([[1, 2],
       [3, 4]])

In [53]:
#addition
m1 + m2

array([[2, 4],
       [6, 8]])

In [54]:
#substraction
m1 - m2

array([[0, 0],
       [0, 0]])

#### Matrix Multiplication

**Definition:** The @ operator performs matrix multiplication according to matrix multiplication rules.


In [55]:
m1 @ m2

array([[ 7, 10],
       [15, 22]])

#### Transpose

**Definition:** The .T attribute swaps the rows and columns of a 2D array.


In [57]:
m1

array([[1, 2],
       [3, 4]])

In [58]:
m1.T

array([[1, 3],
       [2, 4]])

In [59]:
# Alternative matrix multiplication
np.dot(m1, m2)


array([[ 7, 10],
       [15, 22]])

### Array Manipulation

**Definition:** Array manipulation changes the shape of an array or combines arrays while keeping their numerical data.


#### Reshaping

**Definition:** reshape() changes the dimensions of an array without changing its elements.


In [60]:
n2 = np.arange(1,13)
n2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
n2.ndim

1

In [62]:
n2.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### Flattening

**Definition:** flatten() converts a multidimensional array into a one-dimensional copy.


In [63]:
n2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### Concatenation

**Definition:** hstack() joins arrays horizontally, while vstack() joins arrays vertically.


In [64]:
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

In [65]:
np.hstack([n1,n2])

array([10, 20, 30, 40, 50, 60])

In [66]:
n3 = np.vstack([n1,n2])
n3.ndim

2

### Array Broadcasting

**Definition:** Broadcasting allows NumPy to perform element-wise operations on arrays with compatible shapes without manually repeating values.


#### Scalar Broadcasting

**Definition:** A scalar can be applied to every element of an array automatically.


In [67]:
a = np.array([1, 2, 3])
a + 10


array([11, 12, 13])

#### Multi-Dimensional Broadcasting

**Definition:** Compatible dimensions can be automatically expanded so that arrays can participate in element-wise operations.


In [68]:
A = np.array([[1],[2],[3]])   # Shape (3,1)
B = np.array([10,20,30])    # Shape (3,)

A + B


array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

### Array Splitting & Boolean Masking

**Definition:** NumPy can divide arrays into smaller arrays and use Boolean conditions to filter values.


#### Splitting Arrays

**Definition:** np.split() divides an array into multiple sub-arrays.


In [69]:
a = np.arange(12)
np.split(a, 3)


[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

#### Boolean Masking

**Definition:** A Boolean condition creates a True/False mask that can be used to select matching elements.


In [70]:
a = np.array([20,54,34,2,3,55])
a[a > 50]

array([54, 55])

### Copy vs View

**Definition:** A view shares the original array's data, while a copy creates an independent array with separate data.


#### View

**Definition:** view() creates another array object that shares data with the original array.


In [71]:
a = np.array([1, 2, 3])
b = a.view()

b[0] = 100
print(a)
print(b)


[100   2   3]
[100   2   3]


#### Copy

**Definition:** copy() creates an independent copy, so changing it does not change the original array.


In [72]:
a = np.array([1, 2, 3])
c = a.copy()

c[0] = 100
print(a)
print(c)


[1 2 3]
[100   2   3]


### Useful NumPy Functions

**Definition:** NumPy provides functions for finding unique values, sorting arrays, and locating the positions of extreme values.


#### Unique Values

**Definition:** np.unique() returns the unique elements of an array.


In [73]:
a = np.array([3, 1, 2, 3, 2, 1])
np.unique(a)


array([1, 2, 3])

#### Sorting

**Definition:** np.sort() returns a sorted copy of an array.


In [74]:
a = np.array([30, 10, 50, 20])
np.sort(a)


array([10, 20, 30, 50])

#### Maximum and Minimum Index

**Definition:** np.argmax() and np.argmin() return the positions of the maximum and minimum values.


In [75]:
n1 = np.array([12,34,55,87,98,00,43])
n1.argmin()

np.int64(5)

In [76]:
print(np.argmax(n1))
print(np.argmin(n1))


4
5


### Real-World Example: Student Marks

**Definition:** NumPy can summarize a numerical dataset such as student exam scores using descriptive statistics.


In [77]:
marks = np.array([78, 85, 92, 65, 88])

print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(np.std(marks))


81.6
92
65
9.478396488858229


### Aggregation Along Axis

**Definition:** The axis argument controls the direction in which an aggregation is performed on a multidimensional array.


#### axis=0 (Column-Wise)

**Definition:** axis=0 reduces down the rows, producing one result for each column.


In [78]:
a = np.array([[1, 2],
              [3, 4]])

np.sum(a, axis=0)


array([4, 6])

#### axis=1 (Row-Wise)

**Definition:** axis=1 reduces across the columns, producing one result for each row.


In [79]:
a = np.array([[1, 2],
              [3, 4]])

np.sum(a, axis=1)


array([3, 7])

### Searching and Filtering

**Definition:** NumPy provides functions for conditional selection and for locating non-zero or condition-matching positions.


#### np.where()

**Definition:** np.where() selects values based on a condition and can act as a vectorized if-else operation.


In [81]:
a = np.array([1, 6, 3, 8])
np.where(a < 5, a, 10)


array([ 1, 10,  3, 10])

#### np.nonzero()

**Definition:** np.nonzero() returns the indices of elements that are not zero.


In [82]:
a = np.array([0, 5, 0, 8, 2])
np.nonzero(a)


(array([1, 3, 4]),)

#### np.argwhere()

**Definition:** np.argwhere() returns the coordinates of elements satisfying a condition.


In [83]:
a = np.array([1, 6, 3, 8])
np.argwhere(a > 5)


array([[1],
       [3]])

### Handling Missing Values

**Definition:** NumPy represents missing numerical values using np.nan and provides NaN-safe functions for calculations that ignore missing entries.


#### Detecting Missing Values

**Definition:** np.isnan() returns a Boolean mask showing which elements are NaN.


In [87]:
# np.nan

l1 = np.array([1,2,np.nan,4,5,np.nan])
l1

array([ 1.,  2., nan,  4.,  5., nan])

In [88]:
np.isnan(l1)

array([False, False,  True, False, False,  True])

#### NaN-Safe Aggregations

**Definition:** Functions such as np.nansum(), np.nanmean(), and np.nanmax() ignore NaN values during aggregation.


In [90]:
print(np.sum(l1))
print(np.mean(l1))

print(np.nansum(l1))
print(np.nanmean(l1))
print(np.nanmax(l1))


nan
nan
12.0
3.0
5.0


### Iterating Arrays

**Definition:** NumPy arrays can be traversed with Python loops or with NumPy's nditer() iterator.


#### Standard For Loop

**Definition:** A normal loop over a multidimensional array visits one row at a time.


In [91]:
arr = np.array([[1, 2], [3, 4]])

for row in arr:
    print(row)

for row in arr:
    for x in row:
        print(x)


[1 2]
[3 4]
1
2
3
4


#### np.nditer()

**Definition:** np.nditer() provides direct iteration over every element of a multidimensional array.


In [92]:
arr = np.array([[1, 2], [3, 4]])

for x in np.nditer(arr):
    print(x)


1
2
3
4


### Conditional Operations

**Definition:** Vectorized conditional functions allow NumPy to apply if-else style logic efficiently across arrays.


#### np.where() for Conditional Selection

**Definition:** np.where(condition, x, y) chooses x where the condition is True and y where it is False.


In [93]:
arr = np.array([5, 12, 8, 20])
np.where(arr > 10, 10, arr)


array([ 5, 10,  8, 10])

#### np.select() for Multiple Conditions

**Definition:** np.select() evaluates multiple conditions in order and selects the corresponding value for the first matching condition.


In [94]:
val = np.array([-2, 5, 15])

conditions = [val < 0, val > 10]
choices = ['Low', 'High']

np.select(conditions, choices, default='Mid')


array(['Low', 'Mid', 'High'], dtype='<U4')

## Session name :- Pandas ||  Date :- 25/08/2026